
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostfs-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-hostfs-node
  template:
    metadata:
      labels:
        app: csi-hostfs-node
    spec:
      containers:
        - name: node-driver-registrar
          image: csi-node-driver-registrar:latest
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/hostfs.csi.ezcloud.com-reg.sock"]
          args:
            - --v=2
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/hostfs.csi.ezcloud.com/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: hostfs-node-driver
          image: ezcloud/hostfs:v1.0.0
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          args:
            - --v=5
            - --host-dir=/home/data
            - --provisioner-name=$(PROVISIONER_NAME)
            - --nodeid=$(NODE_ID)
            - --hostfs-type=ids,ns
            - --csi-address=$(ADDRESS)
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/hostfs.csi.ezcloud.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
