---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-hostfs-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostfs-controller
  template:
    metadata:
      labels:
        app: csi-hostfs-controller
    spec:
      containers:
        - name: csi-provisioner
          image: csi-provisioner:latest
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=2"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
#        - name: csi-attacher
#          image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
#          args:
#            - "--v=2"
#            - "--csi-address=$(ADDRESS)"
#            - "--leader-election=true"
#          env:
#            - name: ADDRESS
#              value: /csi/csi.sock
#          volumeMounts:
#            - mountPath: /csi
#              name: socket-dir
        - name: csi-hostfs-controller
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: ezcloud/hostfs:v1.0.0
          args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --hostfs-type=ids,cs
            - --csi-address=$(ADDRESS)
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - mountPath: /csi
              name: socket-dir
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
