apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hdd
parameters:
  fsType: xfs
provisioner: hostfs.csi.ezcloud.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
